### ISSUE TITLE
upgrade fails on k3os-based nodes

### ISSUE THREAD

**Issue by billimek** [rancher/k3s-upgrade#20]
When attempting to upgrade with the `rancher/k3s-upgrade:v1.17.4-k3s1` tagged image, the upgrade script fails with,

```
+ upgrade
+ get_k3s_process_info
+ ps -ef
+ grep -E 'k3s .*(server|agent)'
+ grep -E -v '(init|grep|channelserver)'
+ awk '{print $1}'
+ K3S_PID='2429
2431'
+ '[' -z '2429
2431' ]
+ info 'K3S binary is running with pid 2429
2431'
+ echo '[INFO] ' 'K3S binary is running with pid 2429
2431'
[INFO]  K3S binary is running with pid 2429
2431
+ cat /host/proc/2429 2431/cmdline
+ awk '{print $1}'
+ head -n 1
cat: read error: Is a directory
cat: can't open '2431/cmdline': No such file or directory
+ K3S_BIN_PATH=
+ '[' '2429
2431' '==' 1 ]
+ '[' -z  ]
+ fatal 'Failed to fetch the k3s binary path from process 2429
2431'
+ echo '[ERROR] ' 'Failed to fetch the k3s binary path from process 2429
2431'
[ERROR]  Failed to fetch the k3s binary path from process 2429
2431
+ exit 1
```

... This seems to be related to the fact that two different PIDS match the [egreps](https://github.com/rancher/k3s-upgrade/blob/v1.17.4+k3s1/scripts/upgrade.sh#L15):

```
k3os-c [~]$ ps -ef | grep -E "k3s .*(server|agent)" | grep -E -v "(init|grep|channelserver)"
root      2429     1  0 Mar02 ?        00:00:00 supervise-daemon k3s-service --start --stdout /var/log/k3s-service.log --stderr /var/log/k3s-service.log --pidfile /var/run/k3s-service.pid --respawn-delay 5 /sbin/k3s -- agent --node-label k3os.io/mode=local --node-label k3os.io/version=v0.9.1
root      2431  2429  7 Mar02 ?        1-19:46:01 /sbin/k3s agent --node-label k3os.io/mode=local --node-label k3os.io/version=v0.9.1
```

**Comment by billimek** [comment]
Not an issue because k3os should be upgraded in a different way

**Comment by Athosone** [comment]
Hi,
What do you mean it should be upgraded a different way ?

Does this mean we cannot upgrade k3s without upgrading k3os ?

**Comment by dweomer** [comment]
@Athosone for k3OS upgrades leveraging the system-upgrade-controller please see https://github.com/rancher/k3os#automatic-upgrades and https://github.com/rancher/k3os/blob/master/overlay/share/rancher/k3s/server/manifests/system-upgrade-plans/k3os-latest.yaml.

The reason that k3s-upgrade cannot work on k3OS is that it is general purpose and therefore unaware of the special nature of the k3s installation on k3OS, specifically that it is on a read-only mount. This doesn’t mean that it cannot be made to work but that would be a custom plan/script(s)/image as an exercise left to the user.

**Comment by Athosone** [comment]
Ok thanks I understand better :)!
